version: '3.8'

services:
  app:
    build: .
    container_name: wavedeck_app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BASE_URL: ${BASE_URL:-http://localhost:3000}
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    container_name: wavedeck_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: wavedeck_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:
